plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-tidy

baseurl: /website

# Conversion
markdown:    kramdown
highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

collections_dir: _collections
