plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-tidy
  - jekyll-liquify
  - jekyll_inline_highlight


baseurl: /website

# Conversion
markdown:    kramdown
highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge